language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  include:
    - php: 5.4
      env: dependencies=lowest
    - php: 5.6
      env: dependencies=highest

before_install:
  - composer self-update

script:
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-source --prefer-lowest; fi;
  - if [ "$dependencies" = "highest" ]; then composer update --prefer-source; fi;
  - if [ "$dependencies" != "lowest" -a "$dependencies" != "highest" ]; then composer install --dev --prefer-source; fi;
